apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-storage-shared-pvc
  namespace: kubeflow-user-example-com
  labels:
    app.kubernetes.io/name: ai-storage-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
